# Generated by Django 3.1.7 on 2021-04-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            """
                CREATE TABLE IF NOT EXISTS ov.companies (
                    cin bigint NOT NULL PRIMARY KEY,
                    name character varying,
                    br_section character varying,
                    address_line character varying,
                    last_update timestamp without time zone,
                    created_at timestamp without time zone,
                    updated_at timestamp without time zone);
            """),
        migrations.RunSQL(
            """
                INSERT INTO ov.companies(cin, name, br_section, address_line, last_update, created_at, updated_at)
                SELECT  DISTINCT ON (cin) cin,
                        corporate_body_name,
                        br_section,
                        address_line,
                        first_value(updated_at)
                        OVER(PARTITION BY cin ORDER BY updated_at DESC) as last_update,
                        NOW() as created_at,
                        NOW() as updated_at
                FROM ov.or_podanie_issues
                WHERE cin IS NOT NULL
                ON CONFLICT DO NOTHING;
            """),
        migrations.RunSQL(
            """
                INSERT INTO ov.companies(cin, name, br_section, address_line, last_update, created_at, updated_at)
                SELECT  DISTINCT ON (cin) cin,
                     corporate_body_name AS name,
                     br_section,
                     CONCAT(street, ' ', building_number, ' ,', postal_code, ' ', city) as address_line,
                     first_value(updated_at)
                     OVER(PARTITION BY cin ORDER BY updated_at DESC) as last_update,
                     NOW() as created_at,
                     NOW() as updated_at
                FROM ov.likvidator_issues
                WHERE cin IS NOT NULL
                ON CONFLICT DO NOTHING;
            """),
        migrations.RunSQL(
            """
                INSERT INTO ov.companies(cin, name, br_section, address_line, last_update, created_at, updated_at)
                SELECT  DISTINCT ON (cin) cin,
                    corporate_body_name AS name,
                    null,
                    CONCAT(street, ' ', building_number, ' ,', postal_code, ' ', city) as address_line,
                    first_value(updated_at)
                    OVER(PARTITION BY cin ORDER BY updated_at DESC) as last_update,
                    NOW() as created_at,
                    NOW() as updated_at
                FROM ov.konkurz_vyrovnanie_issues
                WHERE cin IS NOT NULL
                ON CONFLICT DO NOTHING;
            """),
        migrations.RunSQL(
            """
                INSERT INTO ov.companies(cin, name, br_section, address_line, last_update, created_at, updated_at)
                SELECT  DISTINCT ON (cin) cin,
                    corporate_body_name AS name,
                    null,
                    CONCAT(street, ' ', building_number, ' ,', postal_code, ' ', city) as address_line,
                    first_value(updated_at)
                    OVER(PARTITION BY cin ORDER BY updated_at DESC) as last_update,
                    NOW() as created_at,
                    NOW() as updated_at
                FROM ov.znizenie_imania_issues
                WHERE cin IS NOT NULL
                ON CONFLICT DO NOTHING;
            """),
        migrations.RunSQL(
            """
                INSERT INTO ov.companies(cin, name, br_section, address_line, last_update, created_at, updated_at)
                SELECT  DISTINCT ON (cin) cin,
                    corporate_body_name AS name,
                    null,
                    CONCAT(street, ' ', building_number, ' ,', postal_code, ' ', city) as address_line,
                    first_value(updated_at)
                    OVER(PARTITION BY cin ORDER BY updated_at DESC) as last_update,
                    NOW() as created_at,
                    NOW() as updated_at
                FROM ov.konkurz_restrukturalizacia_actors
                WHERE cin IS NOT NULL
                ON CONFLICT DO NOTHING;
            """),
        migrations.RunSQL("ALTER TABLE ov.or_podanie_issues ADD COLUMN company_id bigint;"),
        migrations.RunSQL("ALTER TABLE ov.or_podanie_issues ADD FOREIGN KEY (company_id) REFERENCES ov.companies(cin);"),
        migrations.RunSQL("UPDATE ov.or_podanie_issues SET company_id = cin;"),
        
        migrations.RunSQL("ALTER TABLE ov.likvidator_issues ADD COLUMN company_id bigint;"),
        migrations.RunSQL("ALTER TABLE ov.likvidator_issues ADD FOREIGN KEY (company_id) REFERENCES ov.companies(cin);"),
        migrations.RunSQL("UPDATE ov.likvidator_issues SET company_id = cin;"),
                
        migrations.RunSQL("ALTER TABLE ov.konkurz_vyrovnanie_issues ADD COLUMN company_id bigint;"),
        migrations.RunSQL("ALTER TABLE ov.konkurz_vyrovnanie_issues ADD FOREIGN KEY (company_id) REFERENCES ov.companies(cin);"),
        migrations.RunSQL("UPDATE ov.konkurz_vyrovnanie_issues SET company_id = cin;"),

        migrations.RunSQL("ALTER TABLE ov.znizenie_imania_issues ADD COLUMN company_id bigint;"),
        migrations.RunSQL("ALTER TABLE ov.znizenie_imania_issues ADD FOREIGN KEY (company_id) REFERENCES ov.companies(cin);"),
        migrations.RunSQL("UPDATE ov.znizenie_imania_issues SET company_id = cin;"),

        migrations.RunSQL("ALTER TABLE ov.konkurz_restrukturalizacia_actors ADD COLUMN company_id bigint;"),
        migrations.RunSQL("ALTER TABLE ov.konkurz_restrukturalizacia_actors ADD FOREIGN KEY (company_id) REFERENCES ov.companies(cin);"),
        migrations.RunSQL("UPDATE ov.konkurz_restrukturalizacia_actors SET company_id = cin;")
    ]

